urlService: localhost
portService : 7076
spring:
    application:
        name: service1
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://postgres:5432/service1
        username: postgres
        password: 123
    jpa:
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: false
server:
    port: 7075
logging:
    file: ./log.log
    
    
 
 